BEGIN IMMEDIATE;
CREATE TABLE IF NOT EXISTS plans (
 id INTEGER PRIMARY KEY,
 child_id INTEGER NOT NULL REFERENCES children(id),
 level_id INTEGER NOT NULL REFERENCES levels(id),
 model TEXT NOT NULL,
 evidence TEXT NOT NULL,
 content TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS plans_child ON plans(child_id,id DESC);
INSERT OR IGNORE INTO schema_version VALUES (2);
COMMIT;
